# Generated by Django 5.0.2 on 2024-02-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BlogpostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogpost_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpage.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpage.category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogpostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blogpage.blogpostmodel')),
            ],
        ),
    ]
