# Generated by Django 5.0.2 on 2024-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcontent',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='title2',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
