# Generated by Django 5.0.2 on 2024-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0002_rename_text_blogpostcontent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
